### ISSUE TITLE
This is beautiful, how did you pull this off?

### ISSUE THREAD

**Issue by Welding-Torch** [filmicaesthetic/GuitarTabVisualisation#1]
This is one of the most aesthetically pleasing visualizations of poetry that I have seen in the last year, how did you come up with the idea for it?

![image](https://user-images.githubusercontent.com/46340124/162803696-70125ae6-c319-44fb-a329-8af931b06201.png)

And it looks really nice, how did you come up with this graphic?

**Comment by filmicaesthetic** [comment]
Thank you so much!

For everything in this repo, I'm basically following a natural creative process - just exploring the different potential data points within an artform until something clicks.

I went through a lot of different ideas, which all ended up as variations of the streamgraph on the right hand side, until I realised I could visualise the shape of the poem with a simple stacked bar chart.

It certainly helps having freedom to prioritise the aesthetics. Originally, I wanted to visualise all the emotions which was a mess... Cutting that down to the top 3 was purely an aesthetic decision that really tidied things up.

I call this a visual interpretation because it's far more subjective than your average data viz - the inherent uncertainty within the emotion analysis allows for more flexibility in how to present the information.

Hope that helps!
